# Open command in edit mode rather than executing it directly when selected
# from the history.
enter_accept = false

# Use "session" filter when opening atuin via "arrow up" key to get more of
# the "re-run last command" functionality while keeping atuins search/filter
# capabilities.
filter_mode_shell_up_key_binding = "session"
